# Generated by Django 4.0.5 on 2022-08-06 11:45

import advert.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('helps', 'Хилы'), ('dd', 'ДД'), ('sales', 'Торговцы'), ('gildmasters', 'Гилдмастеры'), ('quests', 'Квестигры'), ('blacksmiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('Potions', 'Зельевары'), ('Wizards', 'Мастера заклинаний')], default='tanks', max_length=11)),
                ('text', models.TextField()),
                ('content', models.FileField(upload_to=advert.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
                ('Otvet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.post')),
                ('Otvet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
