# Generated by Django 4.0.5 on 2022-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
